### PR TITLE
Pico SDK build fix

### LINKED ISSUE #68: Fails to build on Raspberry Pi Pico2W
Hey, there appears to be an issue building for RP2350 based Pico2W.
This section doesn't seem correct, it prioritises the ARDUINO ifdef over the PICO_BUILD, which results in the error:
```
.pio\libdeps\pimoroni_pico_plus_2w\OneWireNg\src\platform\Platform_TimeCritical.cpp:19:1: error: 'tc_t' does not name a type
   19 | tc_t _tc[portNUM_PROCESSORS];
      | ^~~~
*** [.pio\build\pimoroni_pico_plus_2w\lib610\OneWireNg\platform\Platform_TimeCritical.cpp.o] Error 1
```
https://github.com/pstolarz/OneWireNg/blob/master/src/platform/Platform_TimeCritical.h#L104-L110

If I move the arduino/mbed ifdef checks after pico_build then the compilation completes as expected.

(I'm building against the pimoroni version of the rp2350 + RP2 wifi module as the [pico2w hasn't made it into the board definitions yet for MaxGerhardt's platformio repo](https://github.com/maxgerhardt/platform-raspberrypi/issues/86).)

### PR DESCRIPTION
**Pull request by pstolarz**
Fixes #68

### CODE REVIEW

File: src/platform/Platform_TimeCritical.h [hunk 1]
```diff
@@ -101,16 +101,10 @@ extern tc_t _tc[portNUM_PROCESSORS];
...
-# define timeCriticalEnter() noInterrupts()
-# define timeCriticalExit() interrupts()
-#elif defined(__MBED__)
-# define timeCriticalEnter() __disable_irq()
-# define timeCriticalExit() __enable_irq()
 #elif defined(PICO_BUILD)
 # include "hardware/sync.h"
 
-#define portNUM_PROCESSORS 2
+# define portNUM_PROCESSORS 2
```
Comment (tyeth) [inline src/platform/Platform_TimeCritical.h:107]: @pstolarz looks like a space slipped in :)
